export const stopWords = new Set([
  "a", "an", "the",
  "and", "or", "but",
  "if", "then", "else",
  "for", "while", "do",
  "of", "at", "by", "with", "about", "against", "between",
  "into", "through", "during", "before", "after", "above", "below",
  "to", "from", "up", "down", "in", "out", "on", "off", "over", "under",
  "again", "further", "once",
  "here", "there", "when", "where", "why", "how",
  "all", "any", "both", "each", "few", "more", "most", "other", "some", "such",
  "no", "nor", "not", "only", "own", "same", "so", "than", "too", "very",
  "can", "will", "just", "should", "now",
  "is", "am", "are", "was", "were", "be", "been", "being",
  "have", "has", "had", "having",
  "do", "does", "did", "doing",
  "i", "me", "my", "myself",
  "we", "our", "ours", "ourselves",
  "you", "your", "yours", "yourself", "yourselves",
  "he", "him", "his", "himself",
  "she", "her", "hers", "herself",
  "it", "its", "itself",
  "they", "them", "their", "theirs", "themselves",
  "this", "that", "these", "those",
  "what", "which", "who", "whom",
  "because", "as", "until", "unless",
  "s", "t", "d", "ll", "m", "o", "re", "ve", "y"
]);